version: "3.2"
services:
  coraticumwebapp:
    restart: always
    container_name: code
    command : bash -c "python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./coraticumWebApp/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - db-net

  frontend:
    restart: always
    container_name: front
    build:
      context: ./coraticum-fe/
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:80"
    stdin_open: true
    depends_on:
      - coraticumwebapp
    networks:
      - db-net


networks:
  db-net:
    driver: bridge