version: "3.2"
services:
  coraticumwebapp:
    hostname: djangoapi
    restart: always
    container_name: code
    build:
      context: ./coraticumWebApp/
      dockerfile: Dockerfile
    command : gunicorn -b 0.0.0.0:9000 config.wsgi --log-file -
    ports:
      - "9000:9000"
    networks:
      - db-net

  coraticum-fe:
    hostname: coraticumfe
    restart: always
    container_name: front
    expose:
      - "3000"
    build:
      context: ./coraticum-fe/
      dockerfile: Dockerfile
    volumes:
      - .:/app/coraticum-fe
      - /app/coraticum-fe/node_modules
    command : npm start
    ports:
      - "80:3000"
    stdin_open: true
    depends_on:
      - coraticumwebapp
    networks:
      - db-net


networks:
  db-net:
    driver: bridge